# VERONICA Security Containment Layer — Default Policy
# This file documents the built-in rules enforced by PolicyEngine.
# Loaded for reference; actual enforcement is in policy_engine.py.
#
# Rule evaluation order: DENY → REQUIRE_APPROVAL → ALLOW → default DENY
# (fail-closed: unknown actions are always denied)

version: "1.0"

# ---------------------------------------------------------------------------
# DENY rules
# ---------------------------------------------------------------------------

deny:
  shell:
    # Block dangerous first-argument commands
    commands:
      - rm
      - del
      - format
      - reg
      - schtasks
      - wmic
      - powershell
      - cmd
      - certutil
      - bitsadmin
      - curl
      - wget
      - scp
      - sftp

    # Block pipe/redirect operators anywhere in the argument list
    operators:
      - "|"
      - ">"
      - ">>"
      - "2>"
      - "&&"
      - ";"

  file_read:
    # Block access to sensitive file paths
    patterns:
      - ".env"
      - ".env.*"
      - "**/AppData/Local/Google/Chrome/User Data/**"
      - "**/.ssh/**"
      - "**/.aws/**"
      - "**/.kube/**"

  net:
    # Block mutating HTTP methods
    methods:
      - POST
      - PUT
      - DELETE
      - PATCH

    # Block GET to hosts not in the allowlist
    get_allowlist:
      - pypi.org
      - files.pythonhosted.org
      - github.com
      - raw.githubusercontent.com
      - registry.npmjs.org

  git:
    # Block sensitive subcommands unless GIT_PUSH_APPROVAL capability is granted
    subcommands:
      - push
      - workflow
      - release
      - tag

# ---------------------------------------------------------------------------
# REQUIRE_APPROVAL rules
# ---------------------------------------------------------------------------

require_approval:
  file_write:
    patterns:
      - ".github/workflows/**"
      - "package.json"
      - ".git/hooks/**"
      - "*.ps1"
      - "*.bat"
      - "*.sh"

  shell:
    # Large file-count changes (metadata.file_count > threshold)
    file_count_threshold: 20

# ---------------------------------------------------------------------------
# ALLOW rules
# ---------------------------------------------------------------------------

allow:
  shell:
    # Safe commands with no pipe/redirect
    commands:
      - pytest
      - python
      - uv
      - npm
      - pnpm
      - cargo
      - go
      - make
      - cmake

# ---------------------------------------------------------------------------
# Default fallback
# ---------------------------------------------------------------------------

default: DENY  # fail-closed — anything not explicitly allowed is denied
