name: Codespell

on:
  pull_request:
  push:
    branches: [main]

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: codespell-project/actions-codespell@v2
        with:
          skip: "*.lock,*.json,*.html,*.log,.git"
          ignore_words_list: "crate,ment,readd,implementors,unparseable,worl,bu,ot,ues,re-use"
